apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: my-cluster-external-secret
spec:
  namespaceSelector:
    matchLabels: 
      cool: cool
  externalSecretName: "my-cluster-external-secret"
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: "1m"
    secretStoreRef:
      name: external-secret-clusters
      kind: ClusterSecretStore
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: demo-secret
    data:
    - secretKey: demo_external_secret
      remoteRef:
        key: demo_external_secret
